#!/bin/sh
# Copyright (C) 2024 YumesomeZakura <1552037053@qq.com>

cpu_usage=$(top -bn1 | grep "CPU:" | awk '{for(i=1;i<=NF;i++) if ($i ~ /idle/) print $(i-1)}' | tr -d '%')
cpu_usage=$(awk -v idle="$cpu_usage" 'BEGIN {printf("%.0f", 100 - idle)}')
nss_avg_utilization=""
connection_count=""
output="CPU: ${cpu_usage}%"

# NSS 利用率
if [ -r "/sys/kernel/debug/qca-nss-drv/stats/cpu_load_ubi" ]; then
	nss_avg_utilization=$(awk 'NR==6 {print $2}' /sys/kernel/debug/qca-nss-drv/stats/cpu_load_ubi)
	[ -n "$nss_avg_utilization" ] && output="$output NSS: ${nss_avg_utilization}"
fi

# ECM 连接数
if [ -r "/sys/kernel/debug/ecm/ecm_db/connection_count_simple" ]; then
	connection_count=$(cat /sys/kernel/debug/ecm/ecm_db/connection_count_simple)
	[ -n "$connection_count" ] && output="$output ECM: ${connection_count}"
fi

echo "$output"
